### ISSUE TITLE
Build errors with imgui

### ISSUE THREAD

**Issue by happydpc** [giordi91/rust-sandbox#1]
Here's the cargo make output:
![image](https://user-images.githubusercontent.com/771776/87115187-1b33e680-c2a5-11ea-991d-c572c7b8ccfe.png)

**Comment by giordi91** [comment]
How are you compiling it? Also, keep in mind that the branch was a rough test. I got imgui to work but craps itself in wasm. I am trying to chase it up on their repo but so far is quiet.

**Comment by happydpc** [comment]
Yes, it's ok when runs on pc. Use wasm cause this error. If imgui can works on browser, that will be great.

**Comment by giordi91** [comment]
Yes that was my goal but seems to be a limitation in the library. I am fairly new to rust etc but this is what I think happens. The wasm work has been done mostly from the Embarks devs, and they do it the way they work internally, which is not super generic. A dev there seems to say might be possible to change it to work in a generic way without breaking their stuff. Not sure if work will be scheduled on it tho. 

What I think happens is that imgui is compiled independently to wasm from c++ with potentially emscripten, then the function modules are set as imports for this wasm function module, the one compiled in rust. That is how you can access imgui functionality. If you enable the wasm feature wasm should build properly but it won't run because fail to find those imports.I did not have time to look into it, so, for now, I am going to camp and see if something changes on the main repo.
